# Generated by Django 5.0.3 on 2025-07-25 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Timetable', '0004_lecturerprofile_studentprofile'),
        ('Users', '0002_alter_lecturerprofile_staff_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturerprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_lecturer_profiles', to='Timetable.department'),
        ),
    ]
