# Generated by Django 5.2.3 on 2025-07-25 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_lecturerprofile_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturerprofile',
            name='department',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
