# Generated by Django 5.0.3 on 2025-05-16 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Timetable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_code', models.CharField(max_length=20, unique=True)),
                ('department', models.CharField(max_length=50)),
                ('college', models.CharField(max_length=50)),
                ('class_size', models.PositiveIntegerField()),
            ],
        ),
    ]
