# Generated by Django 5.0.3 on 2025-05-16 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Timetable', '0002_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('availability', models.JSONField(blank=True, null=True)),
                ('office_location', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('max_courses', models.PositiveIntegerField(default=4)),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='level',
            field=models.PositiveIntegerField(default=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=10, unique=True)),
                ('course_title', models.CharField(max_length=100)),
                ('credit_hours', models.PositiveSmallIntegerField()),
                ('department', models.CharField(max_length=100)),
                ('students_enrolled', models.PositiveIntegerField()),
                ('classes', models.ManyToManyField(related_name='courses', to='Timetable.class')),
                ('course_prerequisites', models.ManyToManyField(blank=True, to='Timetable.course')),
                ('lecturers', models.ManyToManyField(related_name='courses', to='Timetable.lecturer')),
            ],
        ),
    ]
